"""Dell tags from Place

Revision ID: 042145725d4d
Revises: 9173fac332a4
Create Date: 2024-06-17 17:29:33.749961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '042145725d4d'
down_revision: Union[str, None] = '9173fac332a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'tag')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('tag', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
