"""make_many_to_many

Revision ID: 21e736e4d7d2
Revises: c12178d8cd73
Create Date: 2024-06-06 20:28:34.412937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21e736e4d7d2'
down_revision: Union[str, None] = 'c12178d8cd73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place_camera_link',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('place_id', sa.BigInteger(), nullable=False),
    sa.Column('camera_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('places_camera_id_fkey', 'places', type_='foreignkey')
    op.drop_column('places', 'camera_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('camera_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('places_camera_id_fkey', 'places', 'cameras', ['camera_id'], ['id'])
    op.drop_table('place_camera_link')
    # ### end Alembic commands ###
