"""add ip to places

Revision ID: 2585de2295f6
Revises: fc1a5e3f26e3
Create Date: 2024-10-05 08:59:36.731908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2585de2295f6'
down_revision: Union[str, None] = 'fc1a5e3f26e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('ip', sa.String(length=45), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'ip')
    # ### end Alembic commands ###
