"""add tags columt to places

Revision ID: 4b56313b5507
Revises: 21e736e4d7d2
Create Date: 2024-06-11 15:05:43.537019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b56313b5507'
down_revision: Union[str, None] = '21e736e4d7d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('tag', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'tag')
    # ### end Alembic commands ###
