"""add_cameras_table

Revision ID: 9d48337c2ef7
Revises: 9440ff1e007b
Create Date: 2024-06-06 20:12:03.860787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d48337c2ef7'
down_revision: Union[str, None] = '9440ff1e007b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('camera_info', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('places', sa.Column('camera_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'places', 'cameras', ['camera_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'places', type_='foreignkey')
    op.drop_column('places', 'camera_id')
    op.drop_table('cameras')
    # ### end Alembic commands ###
