"""initial migration

Revision ID: a9bf16e95025
Revises: 
Create Date: 2024-06-19 23:17:56.991711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9bf16e95025'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarm_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('tag', sa.Text(), nullable=True),
    sa.Column('camera', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cameras',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('camera_info', sa.JSON(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('places',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('message_thread_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operations_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('place_id', sa.Integer(), nullable=True),
    sa.Column('program', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('dt_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('place_camera_link',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('place_id', sa.BigInteger(), nullable=False),
    sa.Column('camera_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.id'], ),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('place_camera_link')
    op.drop_table('operations_history')
    op.drop_table('places')
    op.drop_table('cameras')
    op.drop_table('alarm_messages')
    # ### end Alembic commands ###
