"""add_column_to_cameras_table

Revision ID: c12178d8cd73
Revises: 9d48337c2ef7
Create Date: 2024-06-06 20:16:21.501071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c12178d8cd73'
down_revision: Union[str, None] = '9d48337c2ef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'comment')
    # ### end Alembic commands ###
