"""add data_for_read column to places

Revision ID: e5848ba692a5
Revises: 2585de2295f6
Create Date: 2024-10-05 11:40:08.454489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5848ba692a5'
down_revision: Union[str, None] = '2585de2295f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('places', sa.Column('data_for_read', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('places', 'data_for_read')
    # ### end Alembic commands ###
