"""change OperationHistory column name

Revision ID: f0726a962ad8
Revises: ff09490fd5a8
Create Date: 2024-05-18 10:44:59.048870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0726a962ad8'
down_revision: Union[str, None] = 'ff09490fd5a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations_history', sa.Column('text', sa.Text(), nullable=True))
    op.drop_column('operations_history', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operations_history', sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('operations_history', 'text')
    # ### end Alembic commands ###
