"""fix alarm_history relationship

Revision ID: fc1a5e3f26e3
Revises: 70ff4708cdcb
Create Date: 2024-10-04 12:43:16.839598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc1a5e3f26e3'
down_revision: Union[str, None] = '70ff4708cdcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
