"""Add places table and modify place_id in OperationHistory

Revision ID: ff09490fd5a8
Revises: 253c107c160d
Create Date: 2024-05-07 14:18:04.870895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'ff09490fd5a8'
down_revision: Union[str, None] = '253c107c160d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
                    sa.Column('id', sa.BigInteger(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=True),
                    sa.Column('comment', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.alter_column('operations_history', 'place_id',
                    existing_type=sa.TEXT(),
                    type_=sa.Integer(),
                    postgresql_using='place_id::integer',  # Добавлено преобразование типа
                    existing_nullable=True)
    op.create_foreign_key(None, 'operations_history', 'places', ['place_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'operations_history', type_='foreignkey')
    op.alter_column('operations_history', 'place_id',
                    existing_type=sa.Integer(),
                    type_=sa.TEXT(),
                    existing_nullable=True)
    op.drop_table('places')
    # ### end Alembic commands ###
